# docker compose build
# docker compose up -d (-d) si pas de log necesseraires (sur serveur ...)

version : '3.8'

services: 
  database:
    container_name: database
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: aafm-back
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  database-test:
    container_name: database-test
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: aafm-back-test
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4307:3306'
    volumes:
      - ./mysql-test:/var/lib/mysql
  php:
    container_name: php
    build:
      context: ./aafm-back
    ports:
      - "9000:9000"
    volumes:
      - ./aafm-back:/var/www/symfony_docker
    depends_on:
      - database
      - database-test
  # nginx-back:
  #   container_name: nginx-back
  #   image: nginx:stable-alpine
  #   ports:
  #     - '8080:80'
  #   volumes:
  #     - ./aafm-back:/var/www/symfony_docker
  #     - ./aafm-back/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - php
  #     - database
  #     - database-test
  nginx-front:
    container_name: nginx-front
    build:
      context: ./aafm-front
    # tty: true  # Allocate a pseudo-TTY for interactive shell
    # stdin_open: true  # Keep STDIN open for interactive shell
    # command: ["/bin/bash"]
    ports:
      - "8081:80"
    volumes:
      # - ./aafm-front:/usr/aafm-front
      - ./aafm-front/nginx/default.conf:/etc/nginx/http.d/default.conf